4) Aplicação da biblioteca NumPy: crie um arquivo ASCII com as temperaturas mínima, máxima e média para cidade 
Rio de Janeiro (arquivo “Dados_climaticos_historicos.xlsx”), organizado por colunas. Assim, demonstre o comando 
numpy.loadtxt para carga de dados e geração de um NumPy array de dimensão: 12 x 3 (12 linhas de registro mensais 
por 3 colunas de temperaturas).       Em seguida, realize print certificando a dimensão (shape) do array, a ocorrência 
do máximo e mínimo valor na coluna de temperatura média. Após, simule as seguintes operações: argsort, reshape, 
transpose, concatenate, split, flip, insert, append, delete.

## Importação de bibliotecas
Utilizamos:
- **openpyxl** para leitura do arquivo Excel;
- **numpy** para manipulação dos dados numéricos.


In [14]:
import openpyxl
import numpy as np

## Leitura do arquivo Excel
Selecionamos a planilha `Historico_Clima_Rio_de_Janeiro` e extraímos:
- Linha 4 → nomes dos meses
- Linha 5 → temperaturas médias
- Linha 6 → temperaturas mínimas
- Linha 7 → temperaturas máximas


In [15]:
arquivo_excel = '../Dados_climaticos_historicos.xlsx'
nome_planilha = 'Historico_Clima_Rio_de_Janeiro'

workbook = openpyxl.load_workbook(arquivo_excel)
planilha = workbook[nome_planilha]

linha_meses = []
for celula in planilha[4][1:]:
    linha_meses.append(celula.value)

linha_media = []
for celula in planilha[5][1:]:
    linha_media.append(celula.value)

linha_minima = []
for celula in planilha[6][1:]:
    linha_minima.append(celula.value)

linha_maxima = []
for celula in planilha[7][1:]:
    linha_maxima.append(celula.value)

## Escrita em arquivo TXT
Criamos um arquivo `Dados_climaticos_historicos.txt` contendo as temperaturas mínimas, máximas e médias,
organizadas em **colunas**.


In [16]:
nome_arquivo_txt = 'Dados_climaticos_historicos_rio.txt'

with open(nome_arquivo_txt, mode='w', encoding='utf-8') as arquivo_txt:
    arquivo_txt.write("Mes\tMinima\tMaxima\tMedia\n")

    for i in range(len(linha_meses)):
        mes = linha_meses[i]
        minima = linha_minima[i]
        maxima = linha_maxima[i]
        media = linha_media[i]

        arquivo_txt.write(f"{mes}\t{minima}\t{maxima}\t{media}\n")

print(f"Arquivo '{nome_arquivo_txt}' gerado com sucesso a partir do Excel!")

Arquivo 'Dados_climaticos_historicos_rio.txt' gerado com sucesso a partir do Excel!


## Carregando os dados no NumPy
Utilizamos o comando `numpy.loadtxt` para carregar as 3 colunas do arquivo TXT.

- `skiprows=1` → pula o cabeçalho
- `usecols=(1,2,3)` → carrega apenas as colunas numéricas
- `unpack=True` → retorna as colunas separadas

Depois aplicamos `transpose` para obter o array no formato `(12,3)`.


In [17]:
array = np.loadtxt(nome_arquivo_txt, skiprows=1, usecols=(1, 2, 3), unpack=True)
array_transposed = array.T
print(array_transposed.shape)

(12, 3)


## Máximo e mínimo da coluna de médias
Aqui identificamos a maior e a menor temperatura média no período analisado.


In [18]:
maior_media = np.max(array_transposed[:, 2])
menor_media = np.min(array_transposed[:, 2])

print(f"Maior valor da temperatura média: {maior_media}")
print(f"Menor valor da temperatura média: {menor_media}")

Maior valor da temperatura média: 27.0
Menor valor da temperatura média: 20.1


## Operações NumPy
A seguir, aplicamos diversos métodos para praticar manipulação de arrays.


### `argsort`
Retorna os índices que ordenam a coluna de médias.


In [19]:

indices_argsort_media = np.argsort(array_transposed[:, 2])
print("Índices ordenados pela temperatura média:", indices_argsort_media)

Índices ordenados pela temperatura média: [ 6  5  7  4  8  9 10  3 11  2  0  1]


### `reshape`
Transformamos o array em um novo formato `6x6` (usando `resize` para preencher).


In [20]:
reshaped_array = np.resize(array_transposed, (6, 6))
print("Array reshape 6x6:\n", reshaped_array)

Array reshape 6x6:
 [[23.3 31.2 26.7 23.3 31.7 27. ]
 [22.7 30.2 25.9 21.1 28.5 24.3]
 [18.2 26.2 21.8 16.8 25.8 20.8]
 [16.  25.4 20.1 16.5 26.5 20.9]
 [18.1 27.5 22.2 20.  28.6 23.7]
 [21.  28.5 24.2 22.4 30.1 25.8]]


### `transpose`
Já aplicamos no carregamento, mas aqui reforçamos: inverte linhas ↔ colunas.


### `concatenate`
Concatenamos o array com ele mesmo na vertical.


In [21]:
# concatenate: concatena array_transposed com ele mesmo na vertical
concatenated_array = np.concatenate((array_transposed, array_transposed), axis=0)
print("Array concatenado verticalmente:\n", concatenated_array)

Array concatenado verticalmente:
 [[23.3 31.2 26.7]
 [23.3 31.7 27. ]
 [22.7 30.2 25.9]
 [21.1 28.5 24.3]
 [18.2 26.2 21.8]
 [16.8 25.8 20.8]
 [16.  25.4 20.1]
 [16.5 26.5 20.9]
 [18.1 27.5 22.2]
 [20.  28.6 23.7]
 [21.  28.5 24.2]
 [22.4 30.1 25.8]
 [23.3 31.2 26.7]
 [23.3 31.7 27. ]
 [22.7 30.2 25.9]
 [21.1 28.5 24.3]
 [18.2 26.2 21.8]
 [16.8 25.8 20.8]
 [16.  25.4 20.1]
 [16.5 26.5 20.9]
 [18.1 27.5 22.2]
 [20.  28.6 23.7]
 [21.  28.5 24.2]
 [22.4 30.1 25.8]]


### `split`
Dividimos o array original em 3 partes iguais.


In [22]:
split_arrays = np.split(array_transposed, 3)
print("Arrays divididos em 3 partes:")
for idx, arr in enumerate(split_arrays):
    print(f"Parte {idx+1}:\n", arr)


Arrays divididos em 3 partes:
Parte 1:
 [[23.3 31.2 26.7]
 [23.3 31.7 27. ]
 [22.7 30.2 25.9]
 [21.1 28.5 24.3]]
Parte 2:
 [[18.2 26.2 21.8]
 [16.8 25.8 20.8]
 [16.  25.4 20.1]
 [16.5 26.5 20.9]]
Parte 3:
 [[18.1 27.5 22.2]
 [20.  28.6 23.7]
 [21.  28.5 24.2]
 [22.4 30.1 25.8]]


### `flip`
Invertemos a ordem das linhas do array.


In [23]:
flipped_array = np.flip(array_transposed, axis=0)
print("Array invertido nas linhas:\n", flipped_array)

Array invertido nas linhas:
 [[22.4 30.1 25.8]
 [21.  28.5 24.2]
 [20.  28.6 23.7]
 [18.1 27.5 22.2]
 [16.5 26.5 20.9]
 [16.  25.4 20.1]
 [16.8 25.8 20.8]
 [18.2 26.2 21.8]
 [21.1 28.5 24.3]
 [22.7 30.2 25.9]
 [23.3 31.7 27. ]
 [23.3 31.2 26.7]]


### `insert`
Inserimos uma coluna de zeros na posição 1.


In [24]:
inserted_array = np.insert(array_transposed, 1, 0, axis=1)
print("Array com coluna de zeros inserida na posição 1:\n", inserted_array)

Array com coluna de zeros inserida na posição 1:
 [[23.3  0.  31.2 26.7]
 [23.3  0.  31.7 27. ]
 [22.7  0.  30.2 25.9]
 [21.1  0.  28.5 24.3]
 [18.2  0.  26.2 21.8]
 [16.8  0.  25.8 20.8]
 [16.   0.  25.4 20.1]
 [16.5  0.  26.5 20.9]
 [18.1  0.  27.5 22.2]
 [20.   0.  28.6 23.7]
 [21.   0.  28.5 24.2]
 [22.4  0.  30.1 25.8]]


### `append`
Adicionamos uma nova linha `[0,0,0]` ao final do array.


In [25]:
nova_linha = np.array([[0, 0, 0]])
appended_array = np.append(array_transposed, nova_linha, axis=0)
print("Array com nova linha adicionada:\n", appended_array)

Array com nova linha adicionada:
 [[23.3 31.2 26.7]
 [23.3 31.7 27. ]
 [22.7 30.2 25.9]
 [21.1 28.5 24.3]
 [18.2 26.2 21.8]
 [16.8 25.8 20.8]
 [16.  25.4 20.1]
 [16.5 26.5 20.9]
 [18.1 27.5 22.2]
 [20.  28.6 23.7]
 [21.  28.5 24.2]
 [22.4 30.1 25.8]
 [ 0.   0.   0. ]]


### `delete`
Removemos a segunda coluna (índice 1).


In [26]:
deleted_array = np.delete(array_transposed, 1, axis=1)
print("Array com segunda coluna removida:\n", deleted_array)

Array com segunda coluna removida:
 [[23.3 26.7]
 [23.3 27. ]
 [22.7 25.9]
 [21.1 24.3]
 [18.2 21.8]
 [16.8 20.8]
 [16.  20.1]
 [16.5 20.9]
 [18.1 22.2]
 [20.  23.7]
 [21.  24.2]
 [22.4 25.8]]
