4) Aplicação da biblioteca NumPy: crie um arquivo ASCII com as temperaturas mínima, máxima e média para cidade 
Rio de Janeiro (arquivo “Dados_climaticos_historicos.xlsx”), organizado por colunas. Assim, demonstre o comando 
numpy.loadtxt para carga de dados e geração de um NumPy array de dimensão: 12 x 3 (12 linhas de registro mensais 
por 3 colunas de temperaturas).       Em seguida, realize print certificando a dimensão (shape) do array, a ocorrência 
do máximo e mínimo valor na coluna de temperatura média. Após, simule as seguintes operações: argsort, reshape, 
transpose, concatenate, split, flip, insert, append, delete.

## Importação de Bibliotecas

Importamos a biblioteca **NumPy** para manipulação dos dados e a nossa biblioteca customizada **`numpy_operacoes_lib`** para as tarefas de preparação e análise dos dados.

In [8]:
import numpy as np
import operacoes_lib as nplib

## 1. Preparação e Carregamento dos Dados

Primeiro, definimos nossas constantes. Em seguida, usamos as funções da nossa biblioteca para:
1.  Ler o arquivo Excel e gerar um arquivo de texto (`.txt`) com 4 colunas (incluindo os meses), exatamente como no notebook original.
2.  Carregar os dados deste `.txt` diretamente para um array NumPy, ignorando a primeira coluna de texto.

In [10]:
# --- Constantes ---
ARQUIVO_EXCEL = '../data/Dados_climaticos_historicos.xlsx'
NOME_PLANILHA = 'Historico_Clima_Rio_de_Janeiro'
ARQUIVO_TXT_SAIDA = '../outputs/Dados_climaticos_historicos_rio.txt'

# 1. Gera o arquivo de texto a partir do Excel, mantendo a coluna de meses
nplib.gerar_arquivo_txt_com_mes(ARQUIVO_EXCEL, NOME_PLANILHA, ARQUIVO_TXT_SAIDA)
print(f"Arquivo '{ARQUIVO_TXT_SAIDA}' gerado com sucesso!")

# 2. Carrega os dados do arquivo de texto para um array NumPy
dados_climaticos_rio = nplib.carregar_dados_climaticos_numpy(ARQUIVO_TXT_SAIDA)

# Certificando a dimensão (shape) do array
print("\nShape do array gerado:")
print(dados_climaticos_rio.shape)

Arquivo '../outputs/Dados_climaticos_historicos_rio.txt' gerado com sucesso!

Shape do array gerado:
(12, 3)


## 2. Análise de Máximo e Mínimo

Com o array carregado, utilizamos a função de análise para encontrar a maior e a menor temperatura média registrada.

In [11]:
# Encontra os valores máximo e mínimo da coluna de médias (índice 2)
maior_media, menor_media = nplib.analisar_temperatura_media(dados_climaticos_rio)

print(f"Maior valor da temperatura média: {maior_media}")
print(f"Menor valor da temperatura média: {menor_media}")

Maior valor da temperatura média: 27.0
Menor valor da temperatura média: 20.1


## 3. Simulação de Operações NumPy

A seguir, aplicamos diversos métodos do NumPy para demonstrar suas funcionalidades de manipulação de arrays.

### `argsort`
Retorna os índices que ordenariam a coluna de temperatura média (coluna 2), do menor para o maior.

In [12]:
indices_ordenados = np.argsort(dados_climaticos_rio[:, 2])
print("Índices que ordenam a coluna de temperatura média:")
print(indices_ordenados)

Índices que ordenam a coluna de temperatura média:
[ 6  5  7  4  8  9 10  3 11  2  0  1]


### `reshape`
Transformamos o array `(12, 3)` em um novo formato `(6, 6)`. Como o novo formato é maior, o `np.resize` repete os dados do array original para preencher o espaço.

In [13]:
reshaped_array = np.resize(dados_climaticos_rio, (6, 6))
print("Array redimensionado para (6, 6):\n", reshaped_array)

Array redimensionado para (6, 6):
 [[23.3 31.2 26.7 23.3 31.7 27. ]
 [22.7 30.2 25.9 21.1 28.5 24.3]
 [18.2 26.2 21.8 16.8 25.8 20.8]
 [16.  25.4 20.1 16.5 26.5 20.9]
 [18.1 27.5 22.2 20.  28.6 23.7]
 [21.  28.5 24.2 22.4 30.1 25.8]]


### `transpose`
Inverte as dimensões do array original, transformando `(12, 3)` em `(3, 12)`.

In [14]:
array_transposto = dados_climaticos_rio.T
print("\nArray transposto (shape: {}):\n".format(array_transposto.shape), array_transposto)


Array transposto (shape: (3, 12)):
 [[23.3 23.3 22.7 21.1 18.2 16.8 16.  16.5 18.1 20.  21.  22.4]
 [31.2 31.7 30.2 28.5 26.2 25.8 25.4 26.5 27.5 28.6 28.5 30.1]
 [26.7 27.  25.9 24.3 21.8 20.8 20.1 20.9 22.2 23.7 24.2 25.8]]


### `concatenate`
Junta (concatena) o array original com ele mesmo ao longo do eixo das linhas (`axis=0`), efetivamente duplicando as linhas.

In [15]:
array_concatenado = np.concatenate((dados_climaticos_rio, dados_climaticos_rio), axis=0)
print("Array concatenado verticalmente (shape: {}):\n".format(array_concatenado.shape), array_concatenado)

Array concatenado verticalmente (shape: (24, 3)):
 [[23.3 31.2 26.7]
 [23.3 31.7 27. ]
 [22.7 30.2 25.9]
 [21.1 28.5 24.3]
 [18.2 26.2 21.8]
 [16.8 25.8 20.8]
 [16.  25.4 20.1]
 [16.5 26.5 20.9]
 [18.1 27.5 22.2]
 [20.  28.6 23.7]
 [21.  28.5 24.2]
 [22.4 30.1 25.8]
 [23.3 31.2 26.7]
 [23.3 31.7 27. ]
 [22.7 30.2 25.9]
 [21.1 28.5 24.3]
 [18.2 26.2 21.8]
 [16.8 25.8 20.8]
 [16.  25.4 20.1]
 [16.5 26.5 20.9]
 [18.1 27.5 22.2]
 [20.  28.6 23.7]
 [21.  28.5 24.2]
 [22.4 30.1 25.8]]


### `split`
Divide o array original em 3 arrays menores de mesmo tamanho.

In [16]:
arrays_divididos = np.split(dados_climaticos_rio, 3)
print("Array dividido em 3 partes:")
for i, arr in enumerate(arrays_divididos):
    print(f"\nParte {i+1}:\n", arr)

Array dividido em 3 partes:

Parte 1:
 [[23.3 31.2 26.7]
 [23.3 31.7 27. ]
 [22.7 30.2 25.9]
 [21.1 28.5 24.3]]

Parte 2:
 [[18.2 26.2 21.8]
 [16.8 25.8 20.8]
 [16.  25.4 20.1]
 [16.5 26.5 20.9]]

Parte 3:
 [[18.1 27.5 22.2]
 [20.  28.6 23.7]
 [21.  28.5 24.2]
 [22.4 30.1 25.8]]


### `flip`
Inverte a ordem dos elementos ao longo de um eixo. Aqui, invertemos a ordem das linhas (`axis=0`).

In [17]:
array_invertido = np.flip(dados_climaticos_rio, axis=0)
print("Array com a ordem das linhas invertida:\n", array_invertido)

Array com a ordem das linhas invertida:
 [[22.4 30.1 25.8]
 [21.  28.5 24.2]
 [20.  28.6 23.7]
 [18.1 27.5 22.2]
 [16.5 26.5 20.9]
 [16.  25.4 20.1]
 [16.8 25.8 20.8]
 [18.2 26.2 21.8]
 [21.1 28.5 24.3]
 [22.7 30.2 25.9]
 [23.3 31.7 27. ]
 [23.3 31.2 26.7]]


### `insert`
Insere uma coluna de zeros na posição de índice 1 (`axis=1`).


In [18]:
array_com_insercao = np.insert(dados_climaticos_rio, 1, 0, axis=1)
print("Array com coluna de zeros inserida:\n", array_com_insercao)

Array com coluna de zeros inserida:
 [[23.3  0.  31.2 26.7]
 [23.3  0.  31.7 27. ]
 [22.7  0.  30.2 25.9]
 [21.1  0.  28.5 24.3]
 [18.2  0.  26.2 21.8]
 [16.8  0.  25.8 20.8]
 [16.   0.  25.4 20.1]
 [16.5  0.  26.5 20.9]
 [18.1  0.  27.5 22.2]
 [20.   0.  28.6 23.7]
 [21.   0.  28.5 24.2]
 [22.4  0.  30.1 25.8]]


### `append`
Adiciona uma nova linha com os valores `[0, 0, 0]` ao final do array.

In [19]:
nova_linha = np.array([[0, 0, 0]])
array_com_append = np.append(dados_climaticos_rio, nova_linha, axis=0)
print("Array com nova linha adicionada ao final:\n", array_com_append)

Array com nova linha adicionada ao final:
 [[23.3 31.2 26.7]
 [23.3 31.7 27. ]
 [22.7 30.2 25.9]
 [21.1 28.5 24.3]
 [18.2 26.2 21.8]
 [16.8 25.8 20.8]
 [16.  25.4 20.1]
 [16.5 26.5 20.9]
 [18.1 27.5 22.2]
 [20.  28.6 23.7]
 [21.  28.5 24.2]
 [22.4 30.1 25.8]
 [ 0.   0.   0. ]]


### `delete`
Remove a segunda coluna (índice 1), que corresponde às temperaturas máximas.

In [20]:
array_com_delecao = np.delete(dados_climaticos_rio, 1, axis=1)
print("Array com a segunda coluna (temp. máxima) removida:\n", array_com_delecao)

Array com a segunda coluna (temp. máxima) removida:
 [[23.3 26.7]
 [23.3 27. ]
 [22.7 25.9]
 [21.1 24.3]
 [18.2 21.8]
 [16.8 20.8]
 [16.  20.1]
 [16.5 20.9]
 [18.1 22.2]
 [20.  23.7]
 [21.  24.2]
 [22.4 25.8]]
